dependencies:
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: jx-app-kuberhealthy
  condition: jx-app-kuberhealthy.enabled
  name: jx-app-kuberhealthy
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.2
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- name: jx-tenant-service
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.761
- name: jx-app-datadog
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.2
- name: lighthouse-githubapp
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.1020
- name: jxui-arcalos
  repository: https://charts.cloudbees.com/cjxd/cloudbees
  version: 0.0.1279
- alias: oauth-proxy-jxui-frontend
  name: oauth2-proxy
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 2.2.2
